### ISSUE TITLE
Slide number for question 35

### ISSUE THREAD

**Issue by nancy11123** [shehab910/SQA-Flashcards#42]
Please add the slide number for question with id: **35**

# Question 35:
### Complete
Iteration starts with iteration ---, which ends in tasks on a task board.  These tasks can be --- in part based on level of --- associated with them.  The aim is to know which tasks should start --- and involve more --- effort.
# Answer found in slide number:
	lectureNo: <PUT LECTURE NUMBER HERE>
	slideNo: <PUT SLIDE NUMBER HERE>

**Comment by shehab910** [comment]
Please add the lecture and slide numbers
